/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('../src/components/basic/buttonPro.vue')['default']
    ButtonPro: typeof import('./../src/components/basic/buttonPro.vue')['default']
    CompTemp: typeof import('./../src/components/CompTemp.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    ProConfigProvider: typeof import('./../src/components/basic/ProConfigProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
